/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiProcessVideoRouteImport } from './routes/api/process-video'
import { Route as ApiAnprPlatesRouteImport } from './routes/api/anpr/plates'
import { Route as ApiEvidenceSplatRouteImport } from './routes/api/evidence/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessVideoRoute = ApiProcessVideoRouteImport.update({
  id: '/api/process-video',
  path: '/api/process-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnprPlatesRoute = ApiAnprPlatesRouteImport.update({
  id: '/api/anpr/plates',
  path: '/api/anpr/plates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenceSplatRoute = ApiEvidenceSplatRouteImport.update({
  id: '/api/evidence/$',
  path: '/api/evidence/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/process-video': typeof ApiProcessVideoRoute
  '/api/anpr/plates': typeof ApiAnprPlatesRoute
  '/api/evidence/$': typeof ApiEvidenceSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/process-video': typeof ApiProcessVideoRoute
  '/api/anpr/plates': typeof ApiAnprPlatesRoute
  '/api/evidence/$': typeof ApiEvidenceSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/process-video': typeof ApiProcessVideoRoute
  '/api/anpr/plates': typeof ApiAnprPlatesRoute
  '/api/evidence/$': typeof ApiEvidenceSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/events'
    | '/api/health'
    | '/api/process-video'
    | '/api/anpr/plates'
    | '/api/evidence/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/events'
    | '/api/health'
    | '/api/process-video'
    | '/api/anpr/plates'
    | '/api/evidence/$'
  id:
    | '__root__'
    | '/'
    | '/api/events'
    | '/api/health'
    | '/api/process-video'
    | '/api/anpr/plates'
    | '/api/evidence/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiProcessVideoRoute: typeof ApiProcessVideoRoute
  ApiAnprPlatesRoute: typeof ApiAnprPlatesRoute
  ApiEvidenceSplatRoute: typeof ApiEvidenceSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-video': {
      id: '/api/process-video'
      path: '/api/process-video'
      fullPath: '/api/process-video'
      preLoaderRoute: typeof ApiProcessVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anpr/plates': {
      id: '/api/anpr/plates'
      path: '/api/anpr/plates'
      fullPath: '/api/anpr/plates'
      preLoaderRoute: typeof ApiAnprPlatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidence/$': {
      id: '/api/evidence/$'
      path: '/api/evidence/$'
      fullPath: '/api/evidence/$'
      preLoaderRoute: typeof ApiEvidenceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiProcessVideoRoute: ApiProcessVideoRoute,
  ApiAnprPlatesRoute: ApiAnprPlatesRoute,
  ApiEvidenceSplatRoute: ApiEvidenceSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
